class TemperatureBuilder
  attr_accessor temperature: Temperature

  def initialize: () -> Temperature

  def type_set: (String from) -> TemperatureBuilder

  def value_set: (Float value) -> TemperatureBuilder

  def convert_to: (String to) -> Float
end
